import { getGeoLocation, getWeather, countDown } from './js/requests'
import { performAction, postData, updateUI} from './js/formHandler'


import './styles/body.scss'
import './styles/entry.scss'
import './styles/footer.scss'
import './styles/header.scss'
import './styles/stylesheet.scss'

export{
    getGeoLocation,
    performAction, 
    getWeather,
    postData,
    updateUI,
    countDown
}

import a01d from './media/icons/a01d.png'
import a01n from './media/icons/a01n.png'
import a02d from './media/icons/a02d.png'
import a02n from './media/icons/a02n.png'
import a03d from './media/icons/a03d.png'
import a03n from './media/icons/a03n.png'
import a04d from './media/icons/a04d.png'
import a04n from './media/icons/a04n.png'
import a05d from './media/icons/a05d.png'
import a05n from './media/icons/a05n.png'
import a06d from './media/icons/a06d.png'
import c01d from './media/icons/c01d.png'
import c01n from './media/icons/c01n.png'
import c02d from './media/icons/c02d.png'
import c02n from './media/icons/c02n.png'
import c03d from './media/icons/c03d.png'
import c03n from './media/icons/c03n.png'
import c04d from './media/icons/c04d.png'
import c04n from './media/icons/c04n.png'
import d01d from './media/icons/d01d.png'
import d01n from './media/icons/d01n.png'
import d02d from './media/icons/d02d.png'
import d02n from './media/icons/d02n.png'
import d03d from './media/icons/d03d.png'
import d03n from './media/icons/d03n.png'
import f01d from './media/icons/f01d.png'
import f01n from './media/icons/f01n.png'
import r01d from './media/icons/r01d.png'
import r01n from './media/icons/r01n.png'
import r02d from './media/icons/r02d.png'
import r02n from './media/icons/r02n.png'
import r03d from './media/icons/r03d.png'
import r03n from './media/icons/r03n.png'
import r04d from './media/icons/r04d.png'
import r04n from './media/icons/r04n.png'
import r05d from './media/icons/r05d.png'
import r05n from './media/icons/r05n.png'
import r06d from './media/icons/r06d.png'
import r06n from './media/icons/r06n.png'
import s01d from './media/icons/s01d.png'
import s01n from './media/icons/s01n.png'
import s02d from './media/icons/s02d.png'
import s02n from './media/icons/s02n.png'
import s03d from './media/icons/s03d.png'
import s03n from './media/icons/s03n.png'
import s04d from './media/icons/s04d.png'
import s04n from './media/icons/s04n.png'
import s05d from './media/icons/s05d.png'
import s05n from './media/icons/s05n.png'
import s06d from './media/icons/s06d.png'
import s06n from './media/icons/s06n.png'
import t01d from './media/icons/t01d.png'
import t01n from './media/icons/t01n.png'
import t02d from './media/icons/t02d.png'
import t02n from './media/icons/t02n.png'
import t03d from './media/icons/t03d.png'
import t03n from './media/icons/t03n.png'
import t04d from './media/icons/t04d.png'
import t04n from './media/icons/t04n.png'
import t05d from './media/icons/t05d.png'
import t05n from './media/icons/t05n.png'
import u00d from './media/icons/u00d.png'
import u00n from './media/icons/u00n.png'
